name: Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ develop, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  unit-test:
    uses: ./.github/workflows/unit_test.yml
  sonar-scanner:
    uses: ./.github/workflows/sonar_scanner.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
